#!/usr/bin/env bash
./syn_dic 轿车 汽车
./syn_dic 宝石 宝物
./syn_dic 旅游 游历
./syn_dic 男孩子 小伙子
./syn_dic 海岸 海滨
./syn_dic 庇护所 精神病院
./syn_dic 魔术师 巫师
./syn_dic 中午 正午
./syn_dic 火炉 炉灶
./syn_dic 食物 水果
./syn_dic 鸟 公鸡
./syn_dic 鸟 鹤
./syn_dic 工具 器械
./syn_dic 兄弟 和尚
./syn_dic 起重机 器械
./syn_dic 小伙子 兄弟
./syn_dic 旅行 轿车
./syn_dic 和尚 圣贤
./syn_dic 墓地 林地
./syn_dic 食物 公鸡
./syn_dic 海岸 丘陵
./syn_dic 森林 墓地
./syn_dic 岸边 林地
./syn_dic 和尚 奴隶
./syn_dic 海岸 森林
./syn_dic 小伙子 巫师
./syn_dic 琴弦 微笑
./syn_dic 玻璃 魔术师
./syn_dic 中午 绳子
./syn_dic 公鸡 旅行
